swapi:
  target: dev
  outputs:
    dev:
      type: postgres
      host: flora.db.elephantsql.com 
      user: nqtjkmnw
      password: RH3fWHJsX7zvQEYIGX_D921HINlHNY59
      port: 5432
      dbname: nqtjkmnw
      schema: public
      threads: 1
      connect_timeout: 10